---
name: Feature Request
description: Suggest a new feature for the project
title: "[Feature]: "
labels: ["enhancement", "feature request"]
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: What is your name?
      placeholder: ex. Sertha Taweewattana
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: dropdown
    id: request-type
    attributes:
      label: Type of request?
      description: Select the type of your request
      options:
        - New Feature
        - Improvement
        - Other
      default: New Feature
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: What is the OS which you want to suggest?
      description: Select the operating system related to your suggestion
      options:
        - Windows
        - macOS
        - Linux
        - Other
      default: Selections
    validations:
      required: true

  - type: textarea
    id: feature-details
    attributes:
      label: What are the details of your suggestion?
      description: Explain what do you want
      placeholder: Feature details!
    validations:
      required: true
---


